networks:
  easy-crit:
    driver: bridge

services:
  redis:
    container_name: session_db
    image: redis:latest
    networks:
      - easy-crit
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data:/data

  app:
    container_name: session_api
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${SESSION_PORT:-8000} --reload
    volumes:
      - .:/app
    ports:
      - "${SESSION_PORT:-8000}:${SESSION_PORT:-8000}"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
