# Ignore some files
exclude = [
  ".git",
  ".ruff_cache",
  ".gitignore",
  "requirements.txt",
  "ruff.toml",
  ".github"
]

line-length = 120
indent-width = 2

target-version = "py312"

[lint]
# Enable pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default;
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules
fixable = ["ALL"]
unfixable = []

# Allow unused variables only when underscore prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "single"
indent-style = "space"

line-ending = "lf"
